apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogging-app
  labels:
    app: blogging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogging
  template:
    metadata:
      labels:
        app: blogging
    spec:
      containers:
        - name: blogging-container
          image:  hamdi2513/bloggingapp:IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"