apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogging-app
  labels:
    app: blogging
spec:
  replicas: 2  # ممكن تزود العدد لو عايز scalability
  selector:
    matchLabels:
      app: blogging
  template:
    metadata:
      labels:
        app: blogging
    spec:
      containers:
        - name: blogging-container
          image: hamdi2513/bloggingapp:45 # <-- استبدل IMAGE_TAG بالـ tag الصحيح للصورة
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"  # مهم تحط "m" بعد الرقم
