apiVersion: v1
kind: Service
metadata:
  name: blogging-service
spec:
  selector:
    app: blogging
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007
  type: NodePort